[platformio]
default_envs = bluepill_f103c8


[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
monitor_speed = 115200

build_flags =
    -Ilib/FreeRTOS/include
    -Ilib/FreeRTOS/portable/GCC/ARM_CM3

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter = +<alarm.cpp> +<system_state.cpp> +<input.cpp> +<hal_mock.cpp>
extra_scripts = pre:build_compiler.py
lib_ignore = FreeRTOS
build_flags =
    -I.
    -Iinclude
