[platformio]
default_envs = bluepill_f103c8


[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
monitor_speed = 115200

build_src_filter =
    +<*.cpp>
    -<hal_mock.cpp>

lib_deps =
    mincrmatt12/STM32Cube Middleware-FreeRTOS
    freertos_port_patch
custom_freertos_config_location = include/FreeRTOSConfig.h
custom_freertos_features = event_groups

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter = +<alarm.cpp> +<system_state.cpp> +<input.cpp> +<hal_mock.cpp>
extra_scripts = pre:build_compiler.py
lib_ignore = STM32Cube Middleware-FreeRTOS,freertos_port_patch
build_flags =
    -I.
    -Iinclude
